### ISSUE TITLE
Your browser doesn't support innerText, so it is not supported. Yet.

### ISSUE THREAD

**Issue by explorigin** [andreineculau/tastebin#1]
Firefox is a pretty major browser.  You should probably work on supporting this before posting to HN.

**Comment by explorigin** [comment]
(but other than that, I like the concept and unique design)

**Comment by andreineculau** [comment]
Pushed a workaround.. Not super comfortable with it, but it looks like it's
working.
Thanks for opening an issue, Timothy

On Thu, Jul 23, 2015 at 2:56 PM, Timothy Farrell notifications@github.com
wrote:

> (but other than that, I like the concept and unique design)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andreineculau/tastebin/issues/1#issuecomment-124086720
> .

## 

andreineculau.com http://www.andreineculau.com

**Comment by explorigin** [comment]
You'll probably be more comfortable with this: 
http://stackoverflow.com/questions/1359469/innertext-works-in-ie-but-not-in-firefox

**Comment by andreineculau** [comment]
I don't know if I'm missing something, but I guess you're talking about the
answer linking to
http://perfectionkills.com/the-poor-misunderstood-innerText/

I read through it before my fix, but couldn't find a solution i.e.
workaround. It basically only reminded me of
http://www.ex-parrot.com/pdw/Mail-RFC822-Address.html :)

Testing my fix briefly, I didn't see any problems, so I can't file a new
issue, or reopen this one.
But for future reference, this is a candidate:
https://github.com/duckinator/innerText-polyfill

On Thu, Jul 23, 2015 at 4:16 PM, Timothy Farrell notifications@github.com
wrote:

> You'll probably be more comfortable with this:
> 
> http://stackoverflow.com/questions/1359469/innertext-works-in-ie-but-not-in-firefox
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andreineculau/tastebin/issues/1#issuecomment-124120931
> .

## 

andreineculau.com http://www.andreineculau.com

**Comment by explorigin** [comment]
I was referring to HTMLElement.textContent but it heavily depends on the whitespace differences.  I didn't read into your code so much as to see how you were using it.
