### ISSUE TITLE
Save by filename--not date

### ISSUE THREAD

**Issue by jungle-boogie** [andreineculau/tastebin#11]
Hello,

At https://frozen-bayou-3399.herokuapp.com/ how do you have the text files saved as the autogenerated file name? In my testing when I go back to the main page of tastebin, it saves by a timestamp:

```
Aug 12 05:28
Jul 30 18:21
Jul 29 13:46
Jul 29 13:45
```

As a result, the file fails to load, but if I access at the autogenerated file name, the data will load.

Example https://frozen-bayou-3399.herokuapp.com/#keyiefornedaxofjefdreelafog.livecodeserver
and at https://frozen-bayou-3399.herokuapp.com/
`2015-08-12 05:27 keyiefornedaxofjefdreelafog` is displayed where keyiefornedaxofjefdreelafog is the link that I can click on to view the text file.

**Comment by andreineculau** [comment]
Not sure that I follow. The "tastes" never have date in the filenames. What might happen is that there is a problem with a. creating the listing of tastes on the server or b. processing the listing (splitting date and filename on each line)

You can try this in your shell

curl http://example.com/tastes

If you see proper date-filename on each line (by proper i mean.. Compare with what you get via curl from my herokuapp) then it's the browser. Otherwise, if smth looks off, it's the server

**Comment by jungle-boogie** [comment]
> If you see proper date-filename on each line (by proper i mean.. Compare with what you get via curl from my herokuapp) then it's the browser. Otherwise, if smth looks off, it's the server

Looks like the server:

```
curl http://example.com:3000/tastes/ 
Aug 12 05:28
Jul 30 18:21
Jul 29 13:46
Jul 29 13:45
```

Any ideas on what I should check to have it match yours:

```
curl https://frozen-bayou-3399.herokuapp.com/tastes/
2015-08-12 05:27 keyiefornedaxofjefdreelafog
```

**Comment by andreineculau** [comment]
Which OS are you running?

**Comment by jungle-boogie** [comment]
> Which OS are you running?

FreeBSD 10.1-RELEASE-p16

You can grab RC3 from here: https://atlas.hashicorp.com/freebsd/
I'll be upgrading to 10.2 next month.

**Comment by andreineculau** [comment]
Thought so :)
I don't know when i'll have the time to try this on bsd but you can grep for "ls" in the .coffee files and try to see which flags/env vars are needed to make the bsd ls command output in the same format as tastebin expects. Meanwhile i should add gnu ls as a dependency. I wanted to stay away from nodejs boilerplating/libs to list files..

Out of curiosity, do you have gnu ls installed as well? Maybe as gnuls or gls? If so, then i can fix easily.

**Comment by jungle-boogie** [comment]
Yep, looks like this is it:
`shCmd = "TIME_STYLE=long-iso ls -tl | head -#{maxListCount} | tail -n +2 | tr -s ' ' | cut -d' ' -f6,7,8"`

Adding `6,7,8,9` includes the tastebin name when listing out in the cli but I don't know what I need to modify to include the link.

**Comment by andreineculau** [comment]
Would you be so kind to try this

ls -tl --time-style=long-iso | head -#{maxListCount} | tail -n +2 | tr -s '
' | cut -d' ' -f6,7,8

and also confirm that "ls -tl" does not print . and .. and hidden files? On
the FreeBSD version where I'm testing this, I also get that, and it
shouldn't happen..

Thanks!

On Wed, Aug 12, 2015 at 6:24 PM, jungle-boogie notifications@github.com
wrote:

> Yep, looks like this is it:
> shCmd = "TIME_STYLE=long-iso ls -tl | head -#{maxListCount} | tail -n +2 |
> tr -s ' ' | cut -d' ' -f6,7,8"
> 
> Adding 6,7,8,9 includes the tastebin name when listing out in the cli but
> I don't know what I need to modify to include the link.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andreineculau/tastebin/issues/11#issuecomment-130361874
> .

## 

andreineculau.com http://www.andreineculau.com

**Comment by jungle-boogie** [comment]
Hello,

At /tastes/ it displays this now:

```
 Aug 12 07:10 grugepofuemujuerigustrofi
 Aug 11 13:49 mufakoloosasutalarechas
 Aug 11 12:29 fulapeloutklatedoogakutuk
 Aug 11 11:45 gukrugecrohisipufuliral
 Aug 11 11:45 sicayetudengeptibcifiror
 Aug 11 08:25 hehocubunofitolpuboonoon
```

But on example.com:30000 it still has the time as the link:

```
Aug 12 07:10
Aug 11 13:49
Aug 11 12:29
Aug 11 11:45
Aug 11 11:45
```

Where would I change it for the link?

**Comment by andreineculau** [comment]
So doing --time-style=long-iso doesn't change the time format on your FreeBSD ????

Please see how you can get ISO format with your la version because that is the problem. The code expects 3 columns: date, time, filename. With the wrong time format like yours, time becomes the filename

**Comment by andreineculau** [comment]
something tells me that on your OS, I'd have to use smth like

ls -tl -D "%F %T"

to get the right format, and that flag is not portable...

Can you look into installing gnuls ? If you can, the latest commit should
solve your problem

On Thu, Aug 13, 2015 at 3:22 PM, Andrei Neculau andrei.neculau@gmail.com
wrote:

> So doing --time-style=long-iso doesn't change the time format on your
> FreeBSD ????
> 
> Please see how you can get ISO format with your la version because that is
> the problem. The code expects 3 columns: date, time, filename. With the
> wrong time format like yours, time becomes the filename
> 
> On 13 Aug 2015, at 15:13, jungle-boogie notifications@github.com wrote:
> 
> Hello,
> 
> At /tastes/ it displays this now:
> 
>  Aug 12 07:10 grugepofuemujuerigustrofi
>  Aug 11 13:49 mufakoloosasutalarechas
>  Aug 11 12:29 fulapeloutklatedoogakutuk
>  Aug 11 11:45 gukrugecrohisipufuliral
>  Aug 11 11:45 sicayetudengeptibcifiror
>  Aug 11 08:25 hehocubunofitolpuboonoon
> 
> But on example.com:30000 it still has the time as the link:
> 
> Aug 12 07:10
> Aug 11 13:49
> Aug 11 12:29
> Aug 11 11:45
> Aug 11 11:45
> 
> Where would I change it for the link?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andreineculau/tastebin/issues/11#issuecomment-130664392
> .

## 

andreineculau.com http://www.andreineculau.com
