### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by jungle-boogie** [andreineculau/tastebin#4]
Hello,

I'd like to say thank you for reviving hastebin in your or rendition. 

Couple things:
0. Do you think line numbers are needed for the horizontal scroll? 
For example: http://tastebin.x-berg.de/#seyizahedekunigfanyey.dns
1. Some of the theme label names disappear when you select it. Try sunburst and you'll see the name is no longer visible.
2. "Distraction free"  makes the text disappear when switching from index. Is that expected behavior?

Thanks and keep up the great work!

Best,
jb

**Comment by andreineculau** [comment]
Sean,
- what do you mean if line numbers are needed? Are you saying you'd like line numbers not to be fixed? You see them more "natural" to scroll with the content? I don't, but then again I also don't think the OSX natural scrolling is natural :)
- disappearing label names - can't reproduce it here. Which browser? Screenshot?
- not sure what is the problem with "distraction free", but please have a go with the latest version. maybe it will still be up at https://frozen-bayou-3399.herokuapp.com/

Cheers

**Comment by jungle-boogie** [comment]
Hi Andrei,

I like and really depend on line number for content; however, I don't think line numbered scroll bars are actually that necessary. Do you? Do we really need to know the line number 5 is for the scroll bar as my example shows?

I'll get screenshots in firefox and chrome, both on Windows.

Things look much better on your link with distraction free. If you commit, I'll update and test. 

thanks,
jb/sean

**Comment by andreineculau** [comment]
Now I understand. So, for better or worse, on save, there's a new line that
gets added (among trimming trailing spaces, etc), so the 5 you see, it's
actually for a 5th line

For instance, if I run `curl
http://tastebin.x-berg.de/tastes/seyizahedekunigfanyey --trace -` in the
end, I see `02f0: 09 09 09 09 09 09 09 09 09 09 09 09 30 0a
............0.` --- 0a stands for new line character.

All is committed

On Wed, Jul 29, 2015 at 12:09 AM, jungle-boogie notifications@github.com
wrote:

> Hi Andrei,
> 
> I like and really depend on line number for content; however, I don't
> think line numbered scroll bars are actually that necessary. Do you? Do we
> really need to know the line number 5 is for the scroll bar as my example
> shows?
> 
> I'll get screenshots in firefox and chrome, both on Windows.
> 
> Things look much better on your link with distraction free. If you commit,
> I'll update and test.
> 
> thanks,
> jb/sean
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andreineculau/tastebin/issues/4#issuecomment-125767543
> .

## 

andreineculau.com http://www.andreineculau.com

**Comment by jungle-boogie** [comment]
Cannot restart tastebin either with forever or npm start:
https://gist.github.com/jungle-boogie/d48e94431d69fa80cca4

**Comment by andreineculau** [comment]
Fixed in 0.9.5

On Wed, Jul 29, 2015 at 1:26 AM, jungle-boogie notifications@github.com
wrote:

> Cannot restart tastebin either with forever or npm start:
> https://gist.github.com/jungle-boogie/d48e94431d69fa80cca4
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andreineculau/tastebin/issues/4#issuecomment-125780806
> .

## 

andreineculau.com http://www.andreineculau.com

**Comment by jungle-boogie** [comment]
> Fixed in 0.9.5

looks great! Thanks.

**Comment by jungle-boogie** [comment]
Hello,

attached image is regarding issue 1 where the theme name is blank. Even if I mouse over the drop down menu, it remains blank.

![blank](https://cloud.githubusercontent.com/assets/1111743/8959099/bcba63d2-35bd-11e5-935a-5bf05da08677.png)

**Comment by andreineculau** [comment]
Can you see the same here https://frozen-bayou-3399.herokuapp.com/ ?
I don't. Try to upgrade to the 0.9.7 I've just pushed and let me know if
things are the same, which browser, OS, etc

On Wed, Jul 29, 2015 at 3:48 PM, jungle-boogie notifications@github.com
wrote:

> Hello,
> 
> attached image is regarding issue 1 where the theme name is blank. Even if
> I mouse over the drop down menu, it remains blank.
> 
> [image: blank]
> https://cloud.githubusercontent.com/assets/1111743/8959099/bcba63d2-35bd-11e5-935a-5bf05da08677.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andreineculau/tastebin/issues/4#issuecomment-125958333
> .

## 

andreineculau.com http://www.andreineculau.com

**Comment by jungle-boogie** [comment]
> Can you see the same here https://frozen-bayou-3399.herokuapp.com/ ?

Don't see it there. I'll update my version. 

I will say that some of the font selections seem to be white on white, making it only possible to see the text once you mouse over the selection.

For example, zenburn.

Firefox 39 on linux.

**Comment by jungle-boogie** [comment]
These these selections also exhibit the same behavior:
dark
darkula
hybrid
monokai
obsidian
pojoaque
rails cat
rainbow
tomowwow-night-eightes
tomowwow-night

Bar far the easiest text to read is if its black.

**Comment by andreineculau** [comment]
please have a go with 0.9.8
https://frozen-bayou-3399.herokuapp.com/

thanks for bringing it up

On Thu, Jul 30, 2015 at 1:28 AM, jungle-boogie notifications@github.com
wrote:

> These these selections also exhibit the same behavior:
> dark
> darkula
> hybrid
> monokai
> obsidian
> pojoaque
> rails cat
> rainbow
> tomowwow-night-eightes
> tomowwow-night
> 
> Bar far the easiest text to read is if its black.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andreineculau/tastebin/issues/4#issuecomment-126126523
> .

## 

andreineculau.com http://www.andreineculau.com

**Comment by jungle-boogie** [comment]
> please have a go with 0.9.8

That's much better!

I think you've corrected all the problems I've found, thank you.
