### ISSUE TITLE
Distraction free distracting

### ISSUE THREAD

**Issue by jungle-boogie** [andreineculau/tastebin#7]
Hello,

Take this example:
https://frozen-bayou-3399.herokuapp.com/#gokreyaruhifobipubrebuef.dns

Set it to distraction free mode and move the window horizontally to the right. For me, the theme selection and index/distraction free drop down bars stay present exactly if you didn't scroll to the right.

![image](https://cloud.githubusercontent.com/assets/1111743/8946666/ffb18ed0-3546-11e5-8c4c-da7948308b74.png)

This is on a linux system using firefox 39.0.

Thanks,
sean

**Comment by andreineculau** [comment]
i see what you mean. will fix

On Wed, Jul 29, 2015 at 1:38 AM, jungle-boogie notifications@github.com
wrote:

> Hello,
> 
> Take this example:
> https://frozen-bayou-3399.herokuapp.com/#gokreyaruhifobipubrebuef.dns
> 
> Set it to distraction free mode and move the window horizontally to the
> right. For me, the theme selection and index/distraction free drop down
> bars stay present exactly if you didn't scroll to the right.
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/1111743/8946666/ffb18ed0-3546-11e5-8c4c-da7948308b74.png
> 
> This is on a linux system using firefox 39.0.
> 
> Thanks,
> sean
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andreineculau/tastebin/issues/7.

## 

andreineculau.com http://www.andreineculau.com

**Comment by jungle-boogie** [comment]
> i see what you mean. will fix 

Much better and confirmed working on Windows chrome.
