### ISSUE TITLE
Raw paste mode?

### ISSUE THREAD

**Issue by jungle-boogie** [andreineculau/tastebin#9]
Hello,

Is it currently possible to get a 'raw' paste view?

If I were to curl/wget/fetch this:
https://frozen-bayou-3399.herokuapp.com/#ascaruckefipaydinorueljak.bash

I'll actually get the html of the page and not the data. 

Thanks,
sean

**Comment by andreineculau** [comment]
there's no link in the UI, but you curl https://frozen-bayou-3399.herokuapp.com/tastes/ascaruckefipaydinorueljak . Please open another ticket if you'd like a link in the UI

PS: "#fragment" does not reach HTTP servers. It's purely for the client
